export const EFFECT_CATALOG = [
  {
    id: "exposure",
    label: "Exposure",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: -2,
    max: 2,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:EXPOSURE|specifics:Type=Exposure",
  },
  {
    id: "contrast",
    label: "Contrast",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: -1,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:CONTRAST|specifics:Type=Contrast",
  },
  {
    id: "saturation",
    label: "Saturation",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: -1,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:SATURATION|shader:assets/filters/base/saturation_fragment.glsl",
  },
  {
    id: "temperature",
    label: "Temperature",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: -1,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:TEMPERATURE|shader:assets/filters/base/whitebalance_fragment.glsl",
  },
  {
    id: "tint",
    label: "Tint",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: -1,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:TINGE|specifics:Type=Tint",
  },
  {
    id: "fade",
    label: "Fade",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:FADED|asset:assets/filters/special/fade.acv",
  },
  {
    id: "highlight",
    label: "Highlight Save",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:HIGHLIGHT|specifics:Type=HighlightsSave",
  },
  {
    id: "shadow",
    label: "Shadow Lift",
    group: "tone",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:SHADOW|specifics:Type=ShadowsSave",
  },
  {
    id: "sharpen",
    label: "Sharpen",
    group: "optical",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:SHARPEN|specifics:Type=Sharpen",
  },
  {
    id: "vignette",
    label: "Vignette",
    group: "overlay",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: true,
    apkAnchor: "enum:VIGNETTE|code:FilterHelper.Oooo0O0(vignette bitmap overlay)",
  },
  {
    id: "lightLeak",
    label: "Light Leak",
    group: "overlay",
    kind: "toggle",
    defaultEnabled: false,
    defaultValue: 0,
    visible: false,
    apkAnchor: "enum:LEAK|specifics:Type=Leak",
  },
  {
    id: "dust",
    label: "Dust",
    group: "overlay",
    kind: "toggle",
    defaultEnabled: false,
    defaultValue: 0,
    visible: false,
    apkAnchor: "enum:DUST|specifics:Type=Dust",
  },
  {
    id: "prism",
    label: "Prism",
    group: "optical",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: false,
    apkAnchor: "enum:PRISM|shader:assets/filters/base/prism_fragment.glsl",
  },
  {
    id: "tilt",
    label: "Tilt",
    group: "optical",
    kind: "slider",
    defaultEnabled: false,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.05,
    visible: false,
    apkAnchor: "enum:TILT|specifics:Type=Tilt",
  },
  {
    id: "date",
    label: "Date",
    group: "overlay",
    kind: "toggle",
    defaultEnabled: false,
    defaultValue: 0,
    visible: false,
    apkAnchor: "enum:DATE|specifics:Type=Date",
  },
];

export const EFFECT_GROUPS = [
  { id: "tone", label: "Tone" },
  { id: "optical", label: "Optical" },
  { id: "overlay", label: "Overlay" },
];

export const VISIBLE_EFFECTS = EFFECT_CATALOG.filter((effect) => effect.visible);

export const EFFECT_DEFAULTS = Object.fromEntries(
  EFFECT_CATALOG.map((effect) => [
    effect.id,
    effect.kind === "toggle"
      ? { enabled: effect.defaultEnabled }
      : { enabled: effect.defaultEnabled, value: effect.defaultValue },
  ]),
);
